import Head from "next/head";
import { Inter } from "@next/font/google";
import styles from "../styles/Home.module.scss";
import classNames from "classnames/bind";
import { useLanguage } from "contexts/LanguageProvider";
import { texts } from "constants/texts";
import LanguageBox from "components/LightTopUtils/LanguageBox";
import BackgroundColorSwitch from "components/LightTopUtils/BackgroundColorSwitch";
import { useTheme } from "contexts/ThemeProvider";
import LightTopMenu from "components/LightTopUtils/LightTopMenu";

const cx = classNames.bind(styles);

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  const { selectedLanguage } = useLanguage();
  const { selectedTextColor, selectedBackground } = useTheme();
  console.log("selectedLanguage ::::: ", selectedLanguage);
  console.log("selectedBackground ::::: ", selectedBackground);

  return (
    <>
      <Head>
        <title>kimyechan</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main
        className={cx({
          main: true,
          [selectedBackground]: true,
        })}
      >
        <LightTopMenu />
        <div>{texts[selectedLanguage].title}</div>
        <div style={{ color: selectedTextColor }}>{selectedTextColor}</div>
      </main>
    </>
  );
}
