import Head from "next/head";
import { Inter } from "@next/font/google";
import styles from "../styles/Home.module.css";
import { useLanguage } from "../contexts/LanguageProvider";
import { texts } from "../constants/texts";
import LanguageBox from "../components/LanguageBox";
import BackgroundColorSwitch from "../components/BackgroundColorSwitch";
import { useTheme } from "../contexts/ThemeProvider";

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  const { selectedLanguage } = useLanguage();
  const { selectedTextColor } = useTheme();
  console.log("selectedLanguage ::::: ", selectedLanguage);

  return (
    <>
      <Head>
        <title>kimyechan</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <LanguageBox />
        <BackgroundColorSwitch />
        <div>{texts[selectedLanguage].title}</div>
        <div style={{ color: selectedTextColor }}>{selectedTextColor}</div>
      </main>
    </>
  );
}
